### ISSUE TITLE
Specify program-wide options?

### ISSUE THREAD

**Issue by Thesola10** [hroptatyr/yuck#11]
Hello,
I would like to be able to define options that would apply to all commands, just like `--help` and `--version`. Here is my current YUCK file
    
    Usage: cz [OPTION]...
    A simple tool to reorganize your code.
    
        -               do not modify the file, write to stdout instead
        -v, --verbose   output more info
        -s, --silent    output less info
        
    Usage: cz copy [FILE] [SECTION] [LINE] [OPTION]...
    Copy a section to a target line number
    
    Usage: cz move [FILE] [SECTION] [LINE] [OPTION]...
    Move a section to a target line number
    
    Usage: cz rm [FILE] [SECTION] [OPTION]...
    Delete a section. 
    
        -c, --cache=DIR Change the cache directory to DIR
    
    Usage: cz restore [FILE] [SECTION] [OPTION]...
    Restore a cached section to where it previously was.
    
        -c, --cache=DIR Change the cache directory to DIR
    
I would like options `-`, `--verbose` and `--silent` to apply on any subcommand.

**Comment by hroptatyr** [comment]
In principle that works as you suggested, however the option consisting of just a dash (`-`) isn't supported.

**Comment by Thesola10** [comment]
Ok, if I have time I will have a look at how to implement that.

**Comment by hroptatyr** [comment]
Well, to be fair it's not hard to implement, the problem is that the single dash is often used to denote stdin or stdout and used as a positional argument.  For instance: `join FILE -`.  The thing about dash options is that they're non-positional, i.e. it doesn't matter if `-s` comes before `-v` or after.  And then there's the thing that single char options can be agglutinated, like `-sv` to mean `-s -v`, the single dash doesn't fit in here either.

To be honest it took me a while to understand how you mean it: `cz copy FILE foo 400 -` would not modify file but instead reproduce the modification on stdout, right?

Why don't you do it sed style and reproduce the modifications on stdout by default with a `-i|--in-place` option to make the operation destructive.  If you look at Unix-ish tools, none of them are destructive by default, thankfully, I rarely get a call to sed right in the first place which would leave me with a bogus file had sed chosen to operate destructively by default.

On the other hand I'm not here to tell you how to do your job, so here's another suggestion that doesn't interfere with current yuck:  Use the `-` as a positional argument, something like:

    yuck_parse(argi, argc, argv);
    ...
    for (size_t i = 0; i < argi->nargs; i++) {
            if (!strcmp(argi->args[i], "-") {
                    /* There's been a - argument on the command line */
                     ...
            }
    }

And then turn the line with the dash into a comment like so:

    Usage: cz copy [FILE] [SECTION] [LINE] [OPTION]... [-]
    Copy a section to a target line number.  Use final - to not modify the file, but to write to stdout instead.

It's just a suggestion.

**Comment by Thesola10** [comment]
What I mean is, can I make it so regular options can be applied to several
commands such as verbose/silent and stdout. Stdout does not have to be a
single dash.

**Comment by hroptatyr** [comment]
Yes, that's the default already.  If you have a general `Usage:` line with no subcommands, all options there can be applied to all subcommands.

**Comment by Thesola10** [comment]
Okay I see
